select*from customer

--Q1 What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender?

--Q2 Which customers used a discount but still spent more than the average purchase amount ?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied='Yes' and purchase_amount >=(SELECT ROUND(AVG(purchase_amount),2) FROM customer)?

--Q3 Which are the top 5 products with the highest average review rating"?

SELECT item_purchased ,ROUND(AVG(review_rating::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG (review_rating)desc
limit 5;

--Q4 Compare the average purchase amount between standard and express shiping?
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

--Q5 Do subscribed customer spend more? compare average spend and total revenue 
--between sbscribers  and non subscribers?

SELECT subscription_status,
COUNT (customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(AVG(purchase_amount),2)AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend desc;

--Q6 Which 5 Product have the highest percentage of purchase with discounts applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes'THEN 1 ELSE 0 END )/COUNT(*),2)AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5;
--Q7 Segment customers into New,Returnning, Loyal based on their total number 
--previous purchase and show the counts of each segment?

WITH customer_type as(
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returnning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer)
SELECT customer_segment,COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--Q8 What are the top 3 most purchased products within each category?
WITH item_counts AS(
SELECT category,
item_purchased,
COUNT (customer_id)AS total_orders,
ROW_NUMBER()OVER(PARTITION BY category ORDER BY COUNT (customer_id)desc) as item_rank
FROM customer
GROUP BY category,item_purchased 
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9 Are customer  who are repeat buyer (more than 5  previous purchases)also likely to subsribe?

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;

--Q10 What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
	 
